config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  resources :contact_form, :path => 'contact', :only => [ :index, :create ], :as => :contacts
  resources :portfolio
  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/email_validatable.rb
require 'mail'

module EmailValidatable
  extend ActiveSupport::Concern

  class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      if !/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.match value
        record.errors[attribute] << (options[:message] || "is not a valid email address")
      end
    end
  end
end

app/models/contact.rb
class Contact
    include ActiveModel::Model, EmailValidatable

    attr_accessor :name, :email, :reason, :contents
    
    validates :name, :reason, :contents, presence: true
    validates :email, email: true, presence: true
end

app/models/portfolio_entry.rb
class PortfolioEntry < ApplicationRecord
    has_one_attached :screenshot

    validates :name, :screenshot, :date, :description, presence: true
end

app/models/site_user.rb
class SiteUser
    include ActiveModel::Model
  
    attr_accessor :username, :password
  
    def login_valid?
      username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASSWORD']
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  ApplicationNotAuthenticated = Class.new(StandardError)

  rescue_from ApplicationNotAuthenticated do
    respond_to do |format|
      format.json { render json: { errors: [message: "401 Not Authorized"] }, status: 401 }
      format.html do
        redirect_to new_session_path, alert: "Access denied.  Please log in."
      end
      format.any { head 401 }
    end
  end

  def authentication_required!
    session[:current_user] || raise(ApplicationNotAuthenticated)
  end
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
    self.per_form_csrf_tokens = true

    def index
        @contact = Contact.new( flash[:params] )
    end

    def create
        @contact = Contact.new( contact_params )

        if verify_recaptcha(action: 'contact', minimum_score: 0.25) && @contact.valid?
            ContactMailer.with( contact: @contact ).message_admin.deliver_now
            flash[:alert] = "Thanks!  Your message has been sent.  Expect a response soon!"

        elsif !verify_recaptcha(action: 'contact', minimum_score: 0.25)
            flash[:params] = @contact
            flash[:error] = "Recaptcha failed.  If you're not a bot, try submitting the form again."
        else
            flash[:params] = @contact
            flash[:error] = "Something doesn't look right with your form.  Check the errors and try again."
        end
        
        redirect_to action: "index"
    end

    def contact_params
        params.require(:contact).permit(:name, :email, :reason, :contents)
    end
end

app/controllers/portfolio_controller.rb
require "mini_magick"

class PortfolioController < ApplicationController
    include ActionView::Helpers::NumberHelper

    def index
        @portfolioEntries = PortfolioEntry.order( date: :desc )
    end

    def new
        authentication_required!
        @portfolioEntry = PortfolioEntry.new( flash[:params] )
        
        @portfolioEntry.date = Date.today unless @portfolioEntry.date
    end

    def create
        authentication_required!
        @portfolioEntry = PortfolioEntry.new( portfolio_entry_params )

        if @portfolioEntry.valid? && @portfolioEntry.save
            flash[:alert] = "Project Added Successfully"
            redirect_to action: "index"
            return
        else
            flash[:error] = "Something went wrong.  Please try again."
        end

        flash[:params] = portfolio_entry_propagated_params
        redirect_to action: "new"
    end

    def destroy
        if PortfolioEntry.delete params[:id]
           flash[:alert] = "Entry deleted successfully."
        else
            flash[:error] = "Something went wrong.  Please try deleting again." 
        end
        redirect_to action: "index"
    end

    def portfolio_entry_params
        params.require(:portfolio_entry).permit(:name, :screenshot, :description, :date, :link)
    end

    def portfolio_entry_propagated_params
        params.require(:portfolio_entry).permit(:name, :description, :date, :link)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @site_user = SiteUser.new( flash[:params] )
      end
    
      def create    
        @site_user = SiteUser.new( site_user_params )
    
        if @site_user.login_valid?
          session[:current_user] = true
          redirect_to '/'
        else
          @site_user.password = nil
          flash[:alert] = "Invalid Login."
          flash[:params] = site_user_params
          redirect_to action: "new"
        end
      end

      def logout
        reset_session
        redirect_to root_path
      end

      def site_user_params
        params.require(:site_user).permit(:username, :password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def nav_link( link_text, link_path, options={} )
        activeClass = current_page?( link_path ) ? 'active' : ''
        puts link_path

        if options[:class]
            options[:class] += ' ' + activeClass
        else
            options = options.merge(:class => activeClass)
        end

        link_to(raw(link_text), link_path, options).html_safe
    end
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact_form/index.html.erb
<div class="page-content with-illustration">
    <%= image_tag "illustrations/email.svg", class: "illustration", alt: "Email Vector" %>
    <div class="contact-text">
        <% if flash[:alert] %>
            <div class="alert alert-success">
                <%=flash[:alert] %>
            </div>
        <% end %>
        <% if flash[:error] %>
            <div class="alert alert-danger">
                <%=flash[:error] %>
            </div>
        <% end %>
        <h1>Contact Me</h1>
        <%= form_for(@contact, url: {action: "create"}) do |form| %>
            <% if @contact.errors.any? %>
                <ul class="alert alert-warning">
                    <% @contact.errors.full_messages.each do |error_message| %>
                        <li><%= error_message %></li>
                    <% end %>
                </ul>
            <% end %>
            <div class="main-form">
                <div>
                    <div class="form-group">
                        <%= form.label :name, "Your Name" %>
                        <%= form.text_field :name, placeholder: "First Last", class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= form.label :email, "Email Address" %>
                        <%= form.text_field :email, placeholder: "name@email.com", class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= form.label :reason, "Reason for Contact" %>
                        <%= form.select( :reason, [["Request for Quote", "rfq"], ["Business Proposition","bp"], ["Personal","p"], ["Other","o"]],{include_blank: "--- Please Select One ---"}, { class: "form-control" }) %>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <%= form.label :contents, "What do you want to say?" %>
                        <%= form.text_area :contents, class: "form-control" %>
                    </div>
                </div>
            </div>
            <%= recaptcha_v3(action: 'contact') %>
            <%= form.submit "Send Me a Message!", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alex Watson: Full Stack Developer</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lato|Acme|Baloo+Bhai&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/brands.css" integrity="sha384-BKw0P+CQz9xmby+uplDwp82Py8x1xtYPK3ORn/ZSoe6Dk3ETP59WCDnX+fI1XCKK" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/solid.css" integrity="sha384-r/k8YTFqmlOaqRkZuSiE9trsrDXkh07mRaoGBMoDcmA58OHILZPsk29i2BsFng1B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/fontawesome.css" integrity="sha384-4aon80D8rXCGx9ayDt85LbyUHeMWd3UiBaWliBlJ53yzm9hqN21A+o1pqoyK04h+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= nav_link 'Home', root_path %></li>
          <li><%= nav_link 'Portfolio', portfolio_index_path %></li>
          <li><%= nav_link '<i class="fab fa-gitlab"></i> Gitlab', 'https://gitlab.com/suniahk', target: :_blank %></li>
          <li><%= nav_link '<i class="fas fa-file-alt"></i> Take a Resume', 'alex_watson_resume.pdf', target: :_blank %></a></li>
          <li><%= nav_link 'Contact', contacts_path %></li>
          <% if session[:current_user] %>
            <li><%= nav_link 'New Portfolio Entry', new_portfolio_path %></li>
            <li><%= nav_link 'Log Out', logout_sessions_path %></li>
          <% end %>
        </ul>
        <i class="fas fa-bars menu-button fa-3x"></i>
      </nav>
    </header>
    <div class="main-content">
      <%= yield %>
    </div>
    <footer>
    </footer>
  </body>
</html>

app/views/portfolio/index.html.erb
<div class="page-content">
    <% if flash[:alert] %>
        <div class="alert alert-success">
            <%=flash[:alert] %>
        </div>
    <% end %>
    <% if flash[:error] %>
        <div class="alert alert-danger">
            <%=flash[:error] %>
        </div>
    <% end %>
    <h1>My Portfolio</h1>
    <% if @portfolioEntries.empty? %>
        <p>There doesn't appear to be anything in my portfolio yet.  Check back soon!</p>
    <% else %>
        <div id="entries">
            <% @portfolioEntries.each do |entry| %>
                <div class="card">
                    <a href="<%= url_for entry.screenshot if entry.screenshot.attached? %>" class="lightbox">
                        <%= image_tag( entry.screenshot.variant( resize: "300x300" ), alt: entry.name, data: { :caption => entry.description } ) if entry.screenshot.attached? %>
                    </a>
                    <div class="card-body">
                        <h5 class="card-title"><% if entry.link && entry.link != "" %><a href="<%= entry.link %>"><%= entry.name %> <i class="fas fa-link"></i></a><% else %><%= entry.name %><% end %></h5>
                        
                    </div>
                    <% if session[:current_user] %>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <%= link_to "Delete", portfolio_path(entry), method: "delete", data: { confirm: "Are you sure you want to delete this entry?"}, class: "btn btn-danger" %>
                            </li>
                        </ul>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

<%= javascript_include_tag 'tobi.min', 'data-turbolinks-track': 'reload' %>

app/views/portfolio/new.html.erb
<div class="page-content">
    <h1>Add New Portfolio Entry</h1>
    <%= form_for(@portfolioEntry, url: {action: "create"}) do |form| %>
        <% if @portfolioEntry.errors.any? %>
            <ul class="alert alert-warning">
                <% @portfolioEntry.errors.full_messages.each do |error_message| %>
                    <li><%= error_message %></li>
                <% end %>
            </ul>
        <% end %>
        <div>
            <div class="form-group">
                <%= form.label :name, "Project Name" %>
                <%= form.text_field :name, placeholder: "Epic Website", class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :screenshot, "Screenshot" %>
                <%= form.file_field :screenshot, class: "form-control-file" %>
            </div>
            <div class="form-group">
                <%= form.label :description, "Description" %>
                <%= form.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :date, "Date Completed" %>
                <%= form.date_field :date, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :link, "URL (Optional)" %>
                <%= form.text_field :link, placeholder: "https://alexwatson.ca", class: "form-control" %>
            </div>
        </div>
        <%= form.submit "Add Project", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/static_pages/index.html.erb
<div class="page-content with-illustration">
    <div class="index-text">
        <h1>Hi, I'm Alex.</h1>
        <p>I'm a Full Stack Developer who emphasizes clean, responsive designs.</p>
        <div class="ctaButtons">
            <%= link_to "See my Work",url_for( controller: 'portfolio', action: 'index' ),class: "btn btn-outline-primary"  %>
            <%= link_to "Send me a message",url_for( controller: 'contact_form', action: 'index' ),class: "btn btn-outline-primary"  %>
        </div>
    </div>
    <%= image_tag "illustrations/web_design.svg", class: "illustration", alt: "Web Design Vector" %>
</div>